sudo: required
services:
  - docker

before_install:
  - docker build -t mw2931/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true mw2931/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-057260469164"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
